[flux-theme]
lazy = true
git-tree-sha1 = "7f89380008f6fda1115500d194ae883b77ca9052"

    [[flux-theme.download]]
    sha256 = "5763c517039f09d2f04205230967ca7d06ce58059ea9279fbc25fcbe3b1cc7c5"
    url = "https://github.com/darsnack/flux-theme/releases/download/v0.1.0/flux-theme-0.1.0.tar.gz"