[flux-theme]
lazy = true
git-tree-sha1 = "d4692593b07cb7dce7a6958cddb834b6bf7cf8ff"

    [[flux-theme.download]]
    sha256 = "4e0b95425c2926c40966863abd69704f46bc12f9009778c6acac7f6b55517835"
    url = "https://github.com/darsnack/flux-theme/releases/download/v0.1.1/flux-theme-0.1.1.tar.gz"